Having repeated problems with GitHub commits
2014-12-07 21:09:16.3396|WARN|thread: 1|StandardUserErrors|Showing user error Failed to create a new commit.
LibGit2Sharp.LockedFileException: The index is locked. This might be due to a concurrent or crashed process