Update plot4.R
I have to make the changes directly on the GitHub copy because my desktop GitHub refuses to commit this file. see log below.
I've tried rebooting to no avail.

2014-12-07 21:09:16.3396|WARN|thread: 1|StandardUserErrors|Showing user error Failed to create a new commit.
LibGit2Sharp.LockedFileException: The index is locked. This might be due to a concurrent or crashed process